name: nss build with kmod

on: workflow_dispatch

jobs:
    build:
        name: nss build with kmod
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Update feed
              run:  scripts/feeds update -a && scripts/feeds install -a

            - name: Generate config with extra kmod
              run:  sh genconfig_nss.sh full

            - name: Build firmware images
              run: make -j$(($(nproc)+1)) world

            - name: Pack kmods
              run:  sh pack_kmods.sh

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-nss-${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-*, kmods.tar.gz
